-- =====================================================================
-- Kindly — tracking schema
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
-- Safe to run more than once.
--
-- Optional. With no Supabase configured the site works completely: reveals
-- are kept in each visitor's own browser and /impact renders the figures
-- committed in src/data/impact-snapshot.json.
--
--   contact_reveals       one row each time someone was shown how to reach a
--                         requester. anon can INSERT and nothing else.
--   confirmed_gifts       gifts BOTH people confirmed. anon can SELECT.
--                         Only you write these, by hand, after matching a pair.
--   site_counters         requests reviewed / published. anon can SELECT.
--   public_impact_totals  the aggregate the site reads. anon can SELECT.
--
-- The anon key in the bundle is public by design. Because of the policies
-- below, the worst anyone can do with it is insert junk reveal rows. They
-- cannot read raw rows, cannot touch confirmed gifts, cannot reach anything
-- else.
-- =====================================================================

-- ---------- contact_reveals --------------------------------------------
-- An INTENT signal, never money. The site keeps this in a separate column
-- from confirmed gifts and the schema keeps them in separate tables, so the
-- two can never be accidentally added together.

create table if not exists public.contact_reveals (
  id            uuid primary key,
  ts            timestamptz not null default now(),
  request_id    text        not null check (char_length(request_id)    between 1 and 80),
  request_title text        not null check (char_length(request_title) between 1 and 200),
  category      text        not null check (char_length(category)      between 1 and 40),
  amount_usd    numeric(10, 2) not null check (amount_usd >= 0 and amount_usd <= 1000),
  source        text        not null check (char_length(source)     <= 120),
  session_id    text        not null check (char_length(session_id) <= 64),
  created_at    timestamptz not null default now()
);

create index if not exists contact_reveals_ts_idx  on public.contact_reveals (ts desc);
create index if not exists contact_reveals_req_idx on public.contact_reveals (request_id);

alter table public.contact_reveals enable row level security;

-- INSERT only. No select, update or delete policy exists for anon, so
-- PostgREST refuses every other verb.
drop policy if exists contact_reveals_anon_insert on public.contact_reveals;
create policy contact_reveals_anon_insert
  on public.contact_reveals
  for insert
  to anon, authenticated
  with check (true);

-- ---------- confirmed_gifts --------------------------------------------
-- The ONLY figures on the site that are ever called money. A row goes in
-- here only when a donor confirmation and a requester confirmation have been
-- matched by hand. The two _confirmed_on dates are stored separately and
-- both are required, so a single-sided "confirmation" cannot be recorded
-- even by accident.

create table if not exists public.confirmed_gifts (
  id                     bigint generated by default as identity primary key,
  request_id             text not null check (char_length(request_id) between 1 and 80),
  amount_usd             numeric(10, 2) not null check (amount_usd > 0 and amount_usd <= 1000),
  donor_confirmed_on     date not null,
  requester_confirmed_on date not null,
  matched_on             date not null default current_date,
  note                   text not null default '' check (char_length(note) <= 500),
  created_at             timestamptz not null default now()
);

create index if not exists confirmed_gifts_matched_idx on public.confirmed_gifts (matched_on desc);

alter table public.confirmed_gifts enable row level security;

drop policy if exists confirmed_gifts_anon_select on public.confirmed_gifts;
create policy confirmed_gifts_anon_select
  on public.confirmed_gifts
  for select
  to anon, authenticated
  using (true);

-- ---------- site_counters ----------------------------------------------
-- Counts only you can know: how many requests you reviewed in total
-- (including the ones you turned down) and how many you published. Publishing
-- the rejection count is deliberate — approval rate is the number that tells a
-- reader whether the review is real.

create table if not exists public.site_counters (
  id                 boolean primary key default true check (id),  -- single row
  requests_reviewed  integer not null default 0 check (requests_reviewed  >= 0),
  requests_published integer not null default 0 check (requests_published >= 0),
  updated_at         timestamptz not null default now()
);

insert into public.site_counters (id) values (true) on conflict (id) do nothing;

alter table public.site_counters enable row level security;

drop policy if exists site_counters_anon_select on public.site_counters;
create policy site_counters_anon_select
  on public.site_counters
  for select
  to anon, authenticated
  using (true);

-- ---------- public read-only views --------------------------------------
-- security_invoker = off (the default, stated explicitly) means these run as
-- the view owner and so can aggregate contact_reveals even though anon cannot
-- read that table. Only the aggregates are ever exposed.

drop view if exists public.public_impact_totals;
create view public.public_impact_totals
  with (security_invoker = off) as
select
  (select coalesce(requests_reviewed, 0)  from public.site_counters limit 1)::bigint  as requests_reviewed,
  (select coalesce(requests_published, 0) from public.site_counters limit 1)::bigint  as requests_published,
  (select count(*)                        from public.contact_reveals)::bigint       as contact_reveals,
  (select count(*)                        from public.confirmed_gifts)::bigint       as confirmed_gifts,
  (select coalesce(sum(amount_usd), 0)    from public.confirmed_gifts)::numeric      as confirmed_usd,
  (select min(ts)                         from public.contact_reveals)               as first_reveal_ts,
  (select max(ts)                         from public.contact_reveals)               as last_reveal_ts;

drop view if exists public.public_confirmed_gifts;
create view public.public_confirmed_gifts
  with (security_invoker = off) as
select
  request_id,
  amount_usd,
  donor_confirmed_on,
  requester_confirmed_on,
  matched_on
from public.confirmed_gifts;

grant select on public.public_impact_totals   to anon, authenticated;
grant select on public.public_confirmed_gifts to anon, authenticated;

-- ---------- recording things -------------------------------------------
-- Update your counters after a review session:
--
--   update public.site_counters
--      set requests_reviewed = 14, requests_published = 8, updated_at = now()
--    where id;
--
-- Record a gift ONLY when you have matched both confirmations:
--
--   insert into public.confirmed_gifts
--     (request_id, amount_usd, donor_confirmed_on, requester_confirmed_on, note)
--   values
--     ('sam-boots', 45.00, '2026-09-04', '2026-09-05',
--      'Donor and requester both confirmed by form');

-- ---------- verification ------------------------------------------------
-- Run these after the script. Expect three tables, two views, three policies.
--
--   select tablename, policyname, cmd from pg_policies
--    where schemaname = 'public' order by tablename;
--
-- Then confirm the lockdown from a terminal. The first must succeed; the
-- second must return an empty array or an error.
--
--   curl -s -X POST "$URL/rest/v1/contact_reveals" \
--     -H "apikey: $ANON" -H "Authorization: Bearer $ANON" \
--     -H "Content-Type: application/json" -H "Prefer: return=minimal" \
--     -d '[{"id":"00000000-0000-4000-8000-000000000001","request_id":"test",
--          "request_title":"Test","category":"other","amount_usd":1,
--          "source":"/test","session_id":"verify"}]'
--
--   curl -s "$URL/rest/v1/contact_reveals?select=*" \
--     -H "apikey: $ANON" -H "Authorization: Bearer $ANON"
--
-- A third check worth doing — anon must NOT be able to write a confirmed gift:
--
--   curl -s -X POST "$URL/rest/v1/confirmed_gifts" \
--     -H "apikey: $ANON" -H "Authorization: Bearer $ANON" \
--     -H "Content-Type: application/json" \
--     -d '[{"request_id":"hack","amount_usd":999,
--          "donor_confirmed_on":"2026-01-01","requester_confirmed_on":"2026-01-01"}]'
--
-- Clean up afterwards:
--   delete from public.contact_reveals where session_id = 'verify';
